[package]
name = "digu"
version = "0.0.2"
edition = "2021"
authors = ["Umran Hussein <umran.hussein@gmail.com>"]
description = "a digu engine written in rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
